### ISSUE TITLE
illuminate/support 5.* ?

### ISSUE THREAD

**Issue by twoSeats** [Anahkiasen/underscore-php#50]
hey there, would it be hard to get support for illuminate/support 5.* for this?

**Comment by mcordingley** [comment]
@twoSeats I was just mucking around in the source for a separate PR and found that illuminate/support 5.* is in the "develop" branch, so I think that's coming next release. But, I don't think that addresses the root cause of your issue.

The real problem is the dependency on illuminate. I'd like if this dependency were broken, so this library wouldn't be tied to the Laravel release cycle. I think this would be the proper solution to @twoSeats's request, as his issue boils down to the release cycles of this library and Larabel being locked in sync. As things stand, if you're stuck on an older version of Laravel then this can't be updated and if you're on a newer version than this library supports, you're again out of luck. I realize that too much functionality depends on that dependency to remove right away, but a migration away from using those functions would do the trick.

For the most part, I think the functionality gained from illuminate/support is easily replicated. The tricky part is string pluralization, which is actually provided by a package that illuminate/support depends upon: [doctrine/inflector.](https://github.com/doctrine/inflector) Just go upstream for that, since it's a hard problem.

**Comment by mikeerickson** [comment]
+1

**Comment by mcordingley** [comment]
All right. I pulled the source code down and have been looking through it for external dependencies. It looks like they're only really found in these files:

- `ArraysMethods`
- `CollectionMethods`
- `FunctionsMethods`
- `NumberMethods`
- `ObjectMethods`
- `StringMethods`

I'm going to sweep and refactor these as I find the time and then send a PR when I'm done.

**Comment by mcordingley** [comment]
`ArraysMethods` is clean.

**Comment by mcordingley** [comment]
`CollectionMethods` is clean.

**Comment by mcordingley** [comment]
`FunctionsMethods` is clean.

**Comment by mcordingley** [comment]
`NumberMethods` is clean.

**Comment by mcordingley** [comment]
`ObjectMethods` is clean.

**Comment by mcordingley** [comment]
Refactored `StringMethods`

**Comment by mcordingley** [comment]
Please ignore all but the latest commit referencing this issue. I did some rebases in my branch to keep things tidy, which means that those commits are no longer part of any branch history. They should go away when GitHub next runs a garbage-collection on my repo.

**Comment by Anahkiasen** [comment]
Closes by #56
